/**
 * LanguageContext — Multi-language support for 6 languages
 * Languages: Arabic (ar), English (en), Chinese (zh), Russian (ru), Persian/Farsi (fa), Turkish (tr)
 * Arabic is the default language. RTL support for Arabic and Persian.
 */
import React, { createContext, useContext, useState, useCallback, useEffect } from "react";

export type Language = "ar" | "en" | "zh" | "ru" | "fa" | "tr";

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  dir: "rtl" | "ltr";
  flag: string;
}

export const LANGUAGES: LanguageInfo[] = [
  { code: "ar", name: "Arabic", nativeName: "العربية", dir: "rtl", flag: "🇸🇦" },
  { code: "en", name: "English", nativeName: "English", dir: "ltr", flag: "🇬🇧" },
  { code: "zh", name: "Chinese", nativeName: "中文", dir: "ltr", flag: "🇨🇳" },
  { code: "ru", name: "Russian", nativeName: "Русский", dir: "ltr", flag: "🇷🇺" },
  { code: "fa", name: "Persian", nativeName: "فارسی", dir: "rtl", flag: "🇮🇷" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", dir: "ltr", flag: "🇹🇷" },
];

interface LanguageContextType {
  lang: Language;
  langInfo: LanguageInfo;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  dir: "rtl" | "ltr";
  isRTL: boolean;
}

const STORAGE_KEY = "maham_language";

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved && LANGUAGES.some(l => l.code === saved)) return saved as Language;
    } catch {}
    return "ar";
  });

  const langInfo = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem(STORAGE_KEY, newLang);
  }, []);

  // Update document direction and lang attribute
  useEffect(() => {
    document.documentElement.dir = langInfo.dir;
    document.documentElement.lang = lang;
  }, [lang, langInfo.dir]);

  const t = useCallback((key: string): string => {
    const translations = allTranslations[lang];
    return translations?.[key] || allTranslations["ar"]?.[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, langInfo, setLang, t, dir: langInfo.dir, isRTL: langInfo.dir === "rtl" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}

// ═══════════════════════════════════════════════════════════════
// TRANSLATIONS — Complete translations for all 6 languages
// ═══════════════════════════════════════════════════════════════
type TranslationMap = Record<string, string>;

const allTranslations: Record<Language, TranslationMap> = {
  // ═══════════════════════════════════════
  // ARABIC (Default)
  // ═══════════════════════════════════════
  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.expos": "المعارض والفعاليات",
    "nav.bookings": "الحجوزات",
    "nav.payments": "المدفوعات",
    "nav.contracts": "العقود",
    "nav.operations": "العمليات",
    "nav.analytics": "التحليلات",
    "nav.ai": "المساعد الذكي",
    "nav.map": "الخريطة",
    "nav.kyc": "توثيق الحساب",
    "nav.help": "مركز المساعدة",
    "nav.settings": "الإعدادات",
    "nav.logout": "تسجيل الخروج",

    // Home / Landing
    "home.title": "بوابة التاجر الذكية",
    "home.subtitle": "Smart Trader Portal",
    "home.desc": "منصة متكاملة لإدارة حجوزاتك في المعارض والمؤتمرات والفعاليات الكبرى — مدعومة بالذكاء الاصطناعي",
    "home.desc2": "A comprehensive AI-powered platform for managing your exhibition, conference & event bookings — from browsing to booking to operations",
    "home.login": "دخول لوحة التحكم",
    "home.browse": "تصفح المعارض والحجز",
    "home.map": "استعراض الخريطة",
    "home.stat.exhibitors": "عارض ومستثمر",
    "home.stat.events": "معرض وفعالية",
    "home.stat.units": "وحدة تجارية",
    "home.stat.satisfaction": "رضا العملاء",

    // Auth
    "auth.phone": "رقم الجوال",
    "auth.phone.placeholder": "05XXXXXXXX",
    "auth.sendOtp": "إرسال رمز التحقق",
    "auth.otp": "رمز التحقق",
    "auth.otp.placeholder": "أدخل الرمز المكون من 4 أرقام",
    "auth.verify": "تحقق",
    "auth.name": "الاسم الكامل",
    "auth.company": "اسم الشركة",
    "auth.activity": "النشاط التجاري",
    "auth.region": "المنطقة",
    "auth.complete": "إكمال التسجيل",
    "auth.welcome": "مرحباً بك في مهام إكسبو",
    "auth.login.title": "تسجيل الدخول",
    "auth.register.title": "إنشاء حساب جديد",

    // Dashboard
    "dash.title": "لوحة التحكم",
    "dash.activeBookings": "حجز نشط",
    "dash.contracts": "عقد صادر",
    "dash.paid": "ريال مدفوع",
    "dash.openEvents": "فعالية متاحة",
    "dash.recentBookings": "آخر الحجوزات",
    "dash.quickActions": "إجراءات سريعة",
    "dash.upcomingEvents": "الفعاليات القادمة",
    "dash.viewAll": "عرض الكل",
    "dash.noBookings": "لا توجد حجوزات بعد",
    "dash.browseStart": "تصفح المعارض وابدأ الحجز",
    "dash.bookNew": "حجز وحدة جديدة",
    "dash.viewContracts": "عرض العقود",
    "dash.makePayment": "سداد دفعة",
    "dash.requestPermit": "طلب تصريح",
    "dash.unitsAvailable": "وحدة متاحة",

    // Browse Expos
    "expos.title": "تصفح المعارض والفعاليات 2026",
    "expos.search": "ابحث عن معرض أو فعالية أو مكان...",
    "expos.all": "الكل",
    "expos.city": "المدينة",
    "expos.sortBy": "ترتيب حسب",
    "expos.sort.date": "التاريخ",
    "expos.sort.price": "السعر",
    "expos.sort.rating": "التقييم",
    "expos.sort.availability": "الوحدات المتاحة",
    "expos.resetFilters": "إعادة تعيين الفلاتر",
    "expos.results": "نتيجة",
    "expos.for": "لـ",
    "expos.noResults": "لا توجد نتائج مطابقة",
    "expos.tryDifferent": "جرب تغيير الفلاتر أو كلمة البحث",
    "expos.featured": "مميز",
    "expos.open": "متاح للحجز",
    "expos.closingSoon": "يغلق قريباً",
    "expos.full": "مكتمل",
    "expos.upcoming": "قريباً",
    "expos.availableUnits": "الوحدات المتاحة",
    "expos.priceRange": "نطاق الأسعار",
    "expos.location": "الموقع",
    "expos.period": "الفترة",
    "expos.venue": "المكان",
    "expos.category": "التصنيف",
    "expos.visitors": "الزوار المتوقعون",
    "expos.occupancy": "نسبة الإشغال",
    "expos.total": "الإجمالي",
    "expos.viewMap": "عرض الخريطة والبوثات",
    "expos.bookNow": "احجز الآن",
    "expos.notifyOpen": "تنبيهي عند فتح الحجز",
    "expos.waitlist": "انضم لقائمة الانتظار",
    "expos.selectUnit": "اختر الوحدة للحجز",
    "expos.bookUnit": "حجز هذه الوحدة",
    "expos.deposit": "عربون",
    "expos.kycRequired": "يجب توثيق حسابك أولاً قبل الحجز",
    "expos.eventsAvailable": "فعاليات متاحة",
    "expos.closingSoonCount": "يغلق قريباً",
    "expos.totalUnits": "إجمالي الوحدات",
    "expos.availableUnitsCount": "وحدات متاحة",
    "expos.remainingCategories": "الفئات المتبقية",
    "expos.sar": "ر.س",

    // Bookings
    "bookings.title": "إدارة الحجوزات",
    "bookings.all": "الكل",
    "bookings.pending": "بانتظار الدفع",
    "bookings.confirmed": "مؤكد",
    "bookings.active": "نشط",
    "bookings.cancelled": "ملغي",
    "bookings.noBookings": "لا توجد حجوزات",
    "bookings.startBrowsing": "ابدأ بتصفح المعارض واحجز وحدتك",
    "bookings.goToPayments": "إكمال الدفع",
    "bookings.viewContract": "عرض العقد",
    "bookings.details": "تفاصيل الحجز",
    "bookings.paid": "مدفوع",
    "bookings.remaining": "متبقي",

    // Payments
    "payments.title": "المدفوعات والفواتير",
    "payments.pending": "مدفوعات معلقة",
    "payments.completed": "مكتملة",
    "payments.all": "الكل",
    "payments.payNow": "ادفع الآن",
    "payments.amount": "المبلغ",
    "payments.method": "طريقة الدفع",
    "payments.creditCard": "بطاقة ائتمان",
    "payments.bankTransfer": "تحويل بنكي",
    "payments.applePay": "Apple Pay",
    "payments.stcPay": "STC Pay",
    "payments.confirmPayment": "تأكيد الدفع",
    "payments.processing": "جاري المعالجة...",
    "payments.success": "تم الدفع بنجاح!",
    "payments.contractGenerated": "تم إصدار العقد تلقائياً",
    "payments.noPending": "لا توجد مدفوعات معلقة",
    "payments.totalPaid": "إجمالي المدفوع",
    "payments.totalRemaining": "إجمالي المتبقي",

    // Contracts
    "contracts.title": "العقود والاتفاقيات",
    "contracts.noContracts": "لا توجد عقود صادرة",
    "contracts.noContractsDesc": "العقد يصدر تلقائياً بعد إكمال الدفع بالكامل",
    "contracts.download": "تحميل PDF",
    "contracts.share": "مشاركة",
    "contracts.signed": "موقّع",
    "contracts.pendingSignature": "بانتظار التوقيع",
    "contracts.draft": "مسودة",
    "contracts.sentVia": "تم الإرسال عبر",
    "contracts.value": "قيمة العقد",
    "contracts.booth": "البوث",
    "contracts.expiry": "تاريخ الانتهاء",
    "contracts.steps": "خطوات إصدار العقد",
    "contracts.step1": "توثيق الحساب (KYC)",
    "contracts.step2": "حجز وحدة في معرض",
    "contracts.step3": "إكمال الدفع بالكامل",
    "contracts.step4": "إصدار العقد تلقائياً",

    // Operations
    "ops.title": "العمليات والخدمات",
    "ops.requestService": "طلب خدمة",
    "ops.permits": "التصاريح",
    "ops.maintenance": "الصيانة",
    "ops.logistics": "اللوجستيات",

    // Analytics
    "analytics.title": "التحليلات والتقارير",
    "analytics.export": "تصدير تقرير",
    "analytics.aiInsights": "رؤى الذكاء الاصطناعي",
    "analytics.totalPaid": "إجمالي المدفوع",
    "analytics.bookings": "عدد الحجوزات",
    "analytics.occupancy": "نسبة الإشغال",
    "analytics.openEvents": "الفعاليات المتاحة",
    "analytics.monthlyDist": "توزيع الفعاليات الشهري 2026",
    "analytics.categoryDist": "توزيع الفعاليات حسب الفئة",
    "analytics.cityUnits": "الوحدات التجارية حسب المدينة",

    // AI Assistant
    "ai.title": "المساعد الذكي",
    "ai.subtitle": "AI Smart Assistant — Powered by MAHAM AI",
    "ai.online": "متصل",
    "ai.thinking": "AI يحلل البيانات...",
    "ai.placeholder": "اسأل AI عن الفعاليات، الحجوزات، التوصيات...",
    "ai.general": "محادثة عامة",
    "ai.analysis": "تحليلات",
    "ai.recommendation": "توصيات",

    // KYC
    "kyc.title": "توثيق الحساب",
    "kyc.subtitle": "تحقق من هويتك لبدء الحجز",
    "kyc.personal": "البيانات الشخصية",
    "kyc.company": "بيانات الشركة",
    "kyc.bank": "الحساب البنكي",
    "kyc.documents": "رفع المستندات",
    "kyc.declaration": "الإقرار القانوني",
    "kyc.complete": "تم التوثيق بنجاح",
    "kyc.next": "التالي",
    "kyc.prev": "السابق",
    "kyc.submit": "إرسال للمراجعة",
    "kyc.uploadFile": "رفع الملف",
    "kyc.uploaded": "تم الرفع",
    "kyc.required": "مطلوب",
    "kyc.optional": "اختياري",

    // Settings
    "settings.title": "الإعدادات",
    "settings.profile": "الملف الشخصي",
    "settings.notifications": "الإشعارات",
    "settings.security": "الأمان",
    "settings.language": "اللغة",
    "settings.theme": "المظهر",
    "settings.dark": "داكن",
    "settings.light": "فاتح",

    // Common
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.confirm": "تأكيد",
    "common.close": "إغلاق",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ",
    "common.success": "تم بنجاح",
    "common.comingSoon": "قريباً",
    "common.viewDetails": "عرض التفاصيل",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.total": "الإجمالي",
    "common.status": "الحالة",
    "common.date": "التاريخ",
    "common.amount": "المبلغ",
    "common.actions": "الإجراءات",
    "common.zone": "المنطقة",
    "common.type": "النوع",
    "common.size": "المساحة",
    "common.price": "السعر",
    "common.services": "الخدمات",
    "common.notifications": "الإشعارات",
    "common.markAllRead": "تعيين الكل كمقروء",
    "common.noNotifications": "لا توجد إشعارات",
  },

  // ═══════════════════════════════════════
  // ENGLISH
  // ═══════════════════════════════════════
  en: {
    "nav.dashboard": "Dashboard",
    "nav.expos": "Exhibitions & Events",
    "nav.bookings": "Bookings",
    "nav.payments": "Payments",
    "nav.contracts": "Contracts",
    "nav.operations": "Operations",
    "nav.analytics": "Analytics",
    "nav.ai": "AI Assistant",
    "nav.map": "Map",
    "nav.kyc": "Account Verification",
    "nav.help": "Help Center",
    "nav.settings": "Settings",
    "nav.logout": "Logout",

    "home.title": "Smart Trader Portal",
    "home.subtitle": "Smart Trader Portal",
    "home.desc": "A comprehensive AI-powered platform for managing your exhibition, conference & event bookings",
    "home.desc2": "From browsing to booking to operations — all in one place",
    "home.login": "Enter Dashboard",
    "home.browse": "Browse Exhibitions & Book",
    "home.map": "View Map",
    "home.stat.exhibitors": "Exhibitors & Investors",
    "home.stat.events": "Exhibitions & Events",
    "home.stat.units": "Commercial Units",
    "home.stat.satisfaction": "Client Satisfaction",

    "auth.phone": "Mobile Number",
    "auth.phone.placeholder": "05XXXXXXXX",
    "auth.sendOtp": "Send Verification Code",
    "auth.otp": "Verification Code",
    "auth.otp.placeholder": "Enter 4-digit code",
    "auth.verify": "Verify",
    "auth.name": "Full Name",
    "auth.company": "Company Name",
    "auth.activity": "Business Activity",
    "auth.region": "Region",
    "auth.complete": "Complete Registration",
    "auth.welcome": "Welcome to Maham Expo",
    "auth.login.title": "Login",
    "auth.register.title": "Create New Account",

    "dash.title": "Dashboard",
    "dash.activeBookings": "Active Bookings",
    "dash.contracts": "Contracts Issued",
    "dash.paid": "SAR Paid",
    "dash.openEvents": "Open Events",
    "dash.recentBookings": "Recent Bookings",
    "dash.quickActions": "Quick Actions",
    "dash.upcomingEvents": "Upcoming Events",
    "dash.viewAll": "View All",
    "dash.noBookings": "No bookings yet",
    "dash.browseStart": "Browse exhibitions and start booking",
    "dash.bookNew": "Book New Unit",
    "dash.viewContracts": "View Contracts",
    "dash.makePayment": "Make Payment",
    "dash.requestPermit": "Request Permit",
    "dash.unitsAvailable": "units available",

    "expos.title": "Browse Exhibitions & Events 2026",
    "expos.search": "Search for an exhibition, event, or venue...",
    "expos.all": "All",
    "expos.city": "City",
    "expos.sortBy": "Sort by",
    "expos.sort.date": "Date",
    "expos.sort.price": "Price",
    "expos.sort.rating": "Rating",
    "expos.sort.availability": "Available Units",
    "expos.resetFilters": "Reset Filters",
    "expos.results": "results",
    "expos.for": "for",
    "expos.noResults": "No matching results",
    "expos.tryDifferent": "Try changing filters or search term",
    "expos.featured": "Featured",
    "expos.open": "Open for Booking",
    "expos.closingSoon": "Closing Soon",
    "expos.full": "Fully Booked",
    "expos.upcoming": "Coming Soon",
    "expos.availableUnits": "Available Units",
    "expos.priceRange": "Price Range",
    "expos.location": "Location",
    "expos.period": "Period",
    "expos.venue": "Venue",
    "expos.category": "Category",
    "expos.visitors": "Expected Visitors",
    "expos.occupancy": "Occupancy Rate",
    "expos.total": "Total",
    "expos.viewMap": "View Map & Booths",
    "expos.bookNow": "Book Now",
    "expos.notifyOpen": "Notify me when booking opens",
    "expos.waitlist": "Join Waitlist",
    "expos.selectUnit": "Select Unit to Book",
    "expos.bookUnit": "Book This Unit",
    "expos.deposit": "Deposit",
    "expos.kycRequired": "Account verification required before booking",
    "expos.eventsAvailable": "Events Available",
    "expos.closingSoonCount": "Closing Soon",
    "expos.totalUnits": "Total Units",
    "expos.availableUnitsCount": "Available Units",
    "expos.remainingCategories": "More Categories",
    "expos.sar": "SAR",

    "bookings.title": "Booking Management",
    "bookings.all": "All",
    "bookings.pending": "Pending Payment",
    "bookings.confirmed": "Confirmed",
    "bookings.active": "Active",
    "bookings.cancelled": "Cancelled",
    "bookings.noBookings": "No bookings",
    "bookings.startBrowsing": "Start browsing exhibitions and book your unit",
    "bookings.goToPayments": "Complete Payment",
    "bookings.viewContract": "View Contract",
    "bookings.details": "Booking Details",
    "bookings.paid": "Paid",
    "bookings.remaining": "Remaining",

    "payments.title": "Payments & Invoices",
    "payments.pending": "Pending Payments",
    "payments.completed": "Completed",
    "payments.all": "All",
    "payments.payNow": "Pay Now",
    "payments.amount": "Amount",
    "payments.method": "Payment Method",
    "payments.creditCard": "Credit Card",
    "payments.bankTransfer": "Bank Transfer",
    "payments.applePay": "Apple Pay",
    "payments.stcPay": "STC Pay",
    "payments.confirmPayment": "Confirm Payment",
    "payments.processing": "Processing...",
    "payments.success": "Payment Successful!",
    "payments.contractGenerated": "Contract auto-generated",
    "payments.noPending": "No pending payments",
    "payments.totalPaid": "Total Paid",
    "payments.totalRemaining": "Total Remaining",

    "contracts.title": "Contracts & Agreements",
    "contracts.noContracts": "No contracts issued",
    "contracts.noContractsDesc": "Contracts are auto-generated after full payment",
    "contracts.download": "Download PDF",
    "contracts.share": "Share",
    "contracts.signed": "Signed",
    "contracts.pendingSignature": "Pending Signature",
    "contracts.draft": "Draft",
    "contracts.sentVia": "Sent via",
    "contracts.value": "Contract Value",
    "contracts.booth": "Booth",
    "contracts.expiry": "Expiry Date",
    "contracts.steps": "Contract Issuance Steps",
    "contracts.step1": "Account Verification (KYC)",
    "contracts.step2": "Book a unit in an exhibition",
    "contracts.step3": "Complete full payment",
    "contracts.step4": "Contract auto-generated",

    "ops.title": "Operations & Services",
    "ops.requestService": "Request Service",
    "ops.permits": "Permits",
    "ops.maintenance": "Maintenance",
    "ops.logistics": "Logistics",

    "analytics.title": "Analytics & Reports",
    "analytics.export": "Export Report",
    "analytics.aiInsights": "AI Insights",
    "analytics.totalPaid": "Total Paid",
    "analytics.bookings": "Bookings",
    "analytics.occupancy": "Occupancy",
    "analytics.openEvents": "Open Events",
    "analytics.monthlyDist": "Monthly Event Distribution 2026",
    "analytics.categoryDist": "Events by Category",
    "analytics.cityUnits": "Units by City",

    "ai.title": "AI Assistant",
    "ai.subtitle": "AI Smart Assistant — Powered by MAHAM AI",
    "ai.online": "Online",
    "ai.thinking": "AI analyzing data...",
    "ai.placeholder": "Ask AI about events, bookings, recommendations...",
    "ai.general": "General Chat",
    "ai.analysis": "Analytics",
    "ai.recommendation": "Recommendations",

    "kyc.title": "Account Verification",
    "kyc.subtitle": "Verify your identity to start booking",
    "kyc.personal": "Personal Information",
    "kyc.company": "Company Information",
    "kyc.bank": "Bank Account",
    "kyc.documents": "Upload Documents",
    "kyc.declaration": "Legal Declaration",
    "kyc.complete": "Verification Complete",
    "kyc.next": "Next",
    "kyc.prev": "Previous",
    "kyc.submit": "Submit for Review",
    "kyc.uploadFile": "Upload File",
    "kyc.uploaded": "Uploaded",
    "kyc.required": "Required",
    "kyc.optional": "Optional",

    "settings.title": "Settings",
    "settings.profile": "Profile",
    "settings.notifications": "Notifications",
    "settings.security": "Security",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.dark": "Dark",
    "settings.light": "Light",

    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.loading": "Loading...",
    "common.error": "Error occurred",
    "common.success": "Success",
    "common.comingSoon": "Coming Soon",
    "common.viewDetails": "View Details",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.total": "Total",
    "common.status": "Status",
    "common.date": "Date",
    "common.amount": "Amount",
    "common.actions": "Actions",
    "common.zone": "Zone",
    "common.type": "Type",
    "common.size": "Size",
    "common.price": "Price",
    "common.services": "Services",
    "common.notifications": "Notifications",
    "common.markAllRead": "Mark all as read",
    "common.noNotifications": "No notifications",
  },

  // ═══════════════════════════════════════
  // CHINESE (中文)
  // ═══════════════════════════════════════
  zh: {
    "nav.dashboard": "控制面板",
    "nav.expos": "展览与活动",
    "nav.bookings": "预订管理",
    "nav.payments": "付款",
    "nav.contracts": "合同",
    "nav.operations": "运营",
    "nav.analytics": "数据分析",
    "nav.ai": "AI助手",
    "nav.map": "地图",
    "nav.kyc": "账户认证",
    "nav.help": "帮助中心",
    "nav.settings": "设置",
    "nav.logout": "退出登录",

    "home.title": "智能商户门户",
    "home.subtitle": "Smart Trader Portal",
    "home.desc": "一站式AI驱动的展览、会议和活动预订管理平台",
    "home.desc2": "从浏览到预订再到运营——一切尽在掌握",
    "home.login": "进入控制面板",
    "home.browse": "浏览展览并预订",
    "home.map": "查看地图",
    "home.stat.exhibitors": "参展商与投资者",
    "home.stat.events": "展览与活动",
    "home.stat.units": "商业单元",
    "home.stat.satisfaction": "客户满意度",

    "auth.phone": "手机号码",
    "auth.phone.placeholder": "05XXXXXXXX",
    "auth.sendOtp": "发送验证码",
    "auth.otp": "验证码",
    "auth.otp.placeholder": "输入4位验证码",
    "auth.verify": "验证",
    "auth.name": "全名",
    "auth.company": "公司名称",
    "auth.activity": "商业活动",
    "auth.region": "地区",
    "auth.complete": "完成注册",
    "auth.welcome": "欢迎来到Maham Expo",
    "auth.login.title": "登录",
    "auth.register.title": "创建新账户",

    "dash.title": "控制面板",
    "dash.activeBookings": "活跃预订",
    "dash.contracts": "已签合同",
    "dash.paid": "已付金额(里亚尔)",
    "dash.openEvents": "开放活动",
    "dash.recentBookings": "最近预订",
    "dash.quickActions": "快捷操作",
    "dash.upcomingEvents": "即将到来的活动",
    "dash.viewAll": "查看全部",
    "dash.noBookings": "暂无预订",
    "dash.browseStart": "浏览展览开始预订",
    "dash.bookNew": "预订新单元",
    "dash.viewContracts": "查看合同",
    "dash.makePayment": "付款",
    "dash.requestPermit": "申请许可",
    "dash.unitsAvailable": "可用单元",

    "expos.title": "浏览2026年展览与活动",
    "expos.search": "搜索展览、活动或场地...",
    "expos.all": "全部",
    "expos.city": "城市",
    "expos.sortBy": "排序方式",
    "expos.sort.date": "日期",
    "expos.sort.price": "价格",
    "expos.sort.rating": "评分",
    "expos.sort.availability": "可用单元",
    "expos.resetFilters": "重置筛选",
    "expos.results": "个结果",
    "expos.for": "搜索",
    "expos.noResults": "没有匹配结果",
    "expos.tryDifferent": "尝试更改筛选条件或搜索词",
    "expos.featured": "精选",
    "expos.open": "开放预订",
    "expos.closingSoon": "即将截止",
    "expos.full": "已满",
    "expos.upcoming": "即将开放",
    "expos.availableUnits": "可用单元",
    "expos.priceRange": "价格范围",
    "expos.location": "位置",
    "expos.period": "时间段",
    "expos.venue": "场馆",
    "expos.category": "类别",
    "expos.visitors": "预计访客",
    "expos.occupancy": "入住率",
    "expos.total": "总计",
    "expos.viewMap": "查看地图和展位",
    "expos.bookNow": "立即预订",
    "expos.notifyOpen": "开放预订时通知我",
    "expos.waitlist": "加入等候名单",
    "expos.selectUnit": "选择预订单元",
    "expos.bookUnit": "预订此单元",
    "expos.deposit": "押金",
    "expos.kycRequired": "预订前需要账户认证",
    "expos.eventsAvailable": "可用活动",
    "expos.closingSoonCount": "即将截止",
    "expos.totalUnits": "总单元数",
    "expos.availableUnitsCount": "可用单元",
    "expos.remainingCategories": "更多类别",
    "expos.sar": "里亚尔",

    "bookings.title": "预订管理",
    "bookings.all": "全部",
    "bookings.pending": "待付款",
    "bookings.confirmed": "已确认",
    "bookings.active": "活跃",
    "bookings.cancelled": "已取消",
    "bookings.noBookings": "暂无预订",
    "bookings.startBrowsing": "开始浏览展览并预订",
    "bookings.goToPayments": "完成付款",
    "bookings.viewContract": "查看合同",
    "bookings.details": "预订详情",
    "bookings.paid": "已付",
    "bookings.remaining": "剩余",

    "payments.title": "付款与发票",
    "payments.pending": "待付款",
    "payments.completed": "已完成",
    "payments.all": "全部",
    "payments.payNow": "立即付款",
    "payments.amount": "金额",
    "payments.method": "付款方式",
    "payments.creditCard": "信用卡",
    "payments.bankTransfer": "银行转账",
    "payments.applePay": "Apple Pay",
    "payments.stcPay": "STC Pay",
    "payments.confirmPayment": "确认付款",
    "payments.processing": "处理中...",
    "payments.success": "付款成功！",
    "payments.contractGenerated": "合同已自动生成",
    "payments.noPending": "无待付款项",
    "payments.totalPaid": "已付总额",
    "payments.totalRemaining": "剩余总额",

    "contracts.title": "合同与协议",
    "contracts.noContracts": "暂无合同",
    "contracts.noContractsDesc": "合同在全额付款后自动生成",
    "contracts.download": "下载PDF",
    "contracts.share": "分享",
    "contracts.signed": "已签署",
    "contracts.pendingSignature": "待签署",
    "contracts.draft": "草稿",
    "contracts.sentVia": "发送方式",
    "contracts.value": "合同价值",
    "contracts.booth": "展位",
    "contracts.expiry": "到期日",
    "contracts.steps": "合同签发步骤",
    "contracts.step1": "账户认证(KYC)",
    "contracts.step2": "在展览中预订单元",
    "contracts.step3": "完成全额付款",
    "contracts.step4": "合同自动生成",

    "ops.title": "运营与服务",
    "ops.requestService": "请求服务",
    "ops.permits": "许可证",
    "ops.maintenance": "维护",
    "ops.logistics": "物流",

    "analytics.title": "数据分析与报告",
    "analytics.export": "导出报告",
    "analytics.aiInsights": "AI洞察",
    "analytics.totalPaid": "已付总额",
    "analytics.bookings": "预订数",
    "analytics.occupancy": "入住率",
    "analytics.openEvents": "开放活动",
    "analytics.monthlyDist": "2026年月度活动分布",
    "analytics.categoryDist": "按类别分布",
    "analytics.cityUnits": "按城市分布",

    "ai.title": "AI助手",
    "ai.subtitle": "AI智能助手 — 由MAHAM AI驱动",
    "ai.online": "在线",
    "ai.thinking": "AI正在分析数据...",
    "ai.placeholder": "向AI询问活动、预订、推荐...",
    "ai.general": "常规对话",
    "ai.analysis": "数据分析",
    "ai.recommendation": "推荐",

    "kyc.title": "账户认证",
    "kyc.subtitle": "验证身份以开始预订",
    "kyc.personal": "个人信息",
    "kyc.company": "公司信息",
    "kyc.bank": "银行账户",
    "kyc.documents": "上传文件",
    "kyc.declaration": "法律声明",
    "kyc.complete": "认证完成",
    "kyc.next": "下一步",
    "kyc.prev": "上一步",
    "kyc.submit": "提交审核",
    "kyc.uploadFile": "上传文件",
    "kyc.uploaded": "已上传",
    "kyc.required": "必填",
    "kyc.optional": "选填",

    "settings.title": "设置",
    "settings.profile": "个人资料",
    "settings.notifications": "通知",
    "settings.security": "安全",
    "settings.language": "语言",
    "settings.theme": "主题",
    "settings.dark": "深色",
    "settings.light": "浅色",

    "common.save": "保存",
    "common.cancel": "取消",
    "common.confirm": "确认",
    "common.close": "关闭",
    "common.back": "返回",
    "common.next": "下一步",
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.success": "成功",
    "common.comingSoon": "即将推出",
    "common.viewDetails": "查看详情",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
    "common.total": "总计",
    "common.status": "状态",
    "common.date": "日期",
    "common.amount": "金额",
    "common.actions": "操作",
    "common.zone": "区域",
    "common.type": "类型",
    "common.size": "面积",
    "common.price": "价格",
    "common.services": "服务",
    "common.notifications": "通知",
    "common.markAllRead": "全部标为已读",
    "common.noNotifications": "暂无通知",
  },

  // ═══════════════════════════════════════
  // RUSSIAN (Русский)
  // ═══════════════════════════════════════
  ru: {
    "nav.dashboard": "Панель управления",
    "nav.expos": "Выставки и мероприятия",
    "nav.bookings": "Бронирования",
    "nav.payments": "Платежи",
    "nav.contracts": "Контракты",
    "nav.operations": "Операции",
    "nav.analytics": "Аналитика",
    "nav.ai": "AI-ассистент",
    "nav.map": "Карта",
    "nav.kyc": "Верификация",
    "nav.help": "Центр помощи",
    "nav.settings": "Настройки",
    "nav.logout": "Выйти",

    "home.title": "Умный портал трейдера",
    "home.subtitle": "Smart Trader Portal",
    "home.desc": "Комплексная AI-платформа для управления бронированиями выставок, конференций и мероприятий",
    "home.desc2": "От просмотра до бронирования и операций — всё в одном месте",
    "home.login": "Войти в панель",
    "home.browse": "Обзор выставок",
    "home.map": "Просмотр карты",
    "home.stat.exhibitors": "Экспоненты и инвесторы",
    "home.stat.events": "Выставки и мероприятия",
    "home.stat.units": "Коммерческие площади",
    "home.stat.satisfaction": "Удовлетворённость клиентов",

    "auth.phone": "Номер телефона",
    "auth.phone.placeholder": "05XXXXXXXX",
    "auth.sendOtp": "Отправить код",
    "auth.otp": "Код подтверждения",
    "auth.otp.placeholder": "Введите 4-значный код",
    "auth.verify": "Подтвердить",
    "auth.name": "Полное имя",
    "auth.company": "Название компании",
    "auth.activity": "Вид деятельности",
    "auth.region": "Регион",
    "auth.complete": "Завершить регистрацию",
    "auth.welcome": "Добро пожаловать в Maham Expo",
    "auth.login.title": "Вход",
    "auth.register.title": "Создать аккаунт",

    "dash.title": "Панель управления",
    "dash.activeBookings": "Активные бронирования",
    "dash.contracts": "Выданные контракты",
    "dash.paid": "Оплачено (SAR)",
    "dash.openEvents": "Открытые мероприятия",
    "dash.recentBookings": "Последние бронирования",
    "dash.quickActions": "Быстрые действия",
    "dash.upcomingEvents": "Предстоящие мероприятия",
    "dash.viewAll": "Показать все",
    "dash.noBookings": "Нет бронирований",
    "dash.browseStart": "Просмотрите выставки и начните бронирование",
    "dash.bookNew": "Забронировать площадь",
    "dash.viewContracts": "Просмотр контрактов",
    "dash.makePayment": "Оплатить",
    "dash.requestPermit": "Запросить разрешение",
    "dash.unitsAvailable": "доступных площадей",

    "expos.title": "Выставки и мероприятия 2026",
    "expos.search": "Поиск выставки, мероприятия или площадки...",
    "expos.all": "Все",
    "expos.city": "Город",
    "expos.sortBy": "Сортировать по",
    "expos.sort.date": "Дата",
    "expos.sort.price": "Цена",
    "expos.sort.rating": "Рейтинг",
    "expos.sort.availability": "Доступные площади",
    "expos.resetFilters": "Сбросить фильтры",
    "expos.results": "результатов",
    "expos.for": "для",
    "expos.noResults": "Нет результатов",
    "expos.tryDifferent": "Попробуйте изменить фильтры",
    "expos.featured": "Рекомендуемое",
    "expos.open": "Открыто для бронирования",
    "expos.closingSoon": "Скоро закрытие",
    "expos.full": "Полностью забронировано",
    "expos.upcoming": "Скоро",
    "expos.availableUnits": "Доступные площади",
    "expos.priceRange": "Диапазон цен",
    "expos.location": "Местоположение",
    "expos.period": "Период",
    "expos.venue": "Площадка",
    "expos.category": "Категория",
    "expos.visitors": "Ожидаемые посетители",
    "expos.occupancy": "Заполняемость",
    "expos.total": "Всего",
    "expos.viewMap": "Карта и стенды",
    "expos.bookNow": "Забронировать",
    "expos.notifyOpen": "Уведомить при открытии",
    "expos.waitlist": "В лист ожидания",
    "expos.selectUnit": "Выберите площадь",
    "expos.bookUnit": "Забронировать",
    "expos.deposit": "Депозит",
    "expos.kycRequired": "Требуется верификация аккаунта",
    "expos.eventsAvailable": "Доступных мероприятий",
    "expos.closingSoonCount": "Скоро закрытие",
    "expos.totalUnits": "Всего площадей",
    "expos.availableUnitsCount": "Доступных площадей",
    "expos.remainingCategories": "Ещё категории",
    "expos.sar": "SAR",

    "bookings.title": "Управление бронированиями",
    "bookings.all": "Все",
    "bookings.pending": "Ожидает оплаты",
    "bookings.confirmed": "Подтверждено",
    "bookings.active": "Активно",
    "bookings.cancelled": "Отменено",
    "bookings.noBookings": "Нет бронирований",
    "bookings.startBrowsing": "Начните просмотр выставок",
    "bookings.goToPayments": "Оплатить",
    "bookings.viewContract": "Просмотр контракта",
    "bookings.details": "Детали бронирования",
    "bookings.paid": "Оплачено",
    "bookings.remaining": "Остаток",

    "payments.title": "Платежи и счета",
    "payments.pending": "Ожидающие платежи",
    "payments.completed": "Завершённые",
    "payments.all": "Все",
    "payments.payNow": "Оплатить сейчас",
    "payments.amount": "Сумма",
    "payments.method": "Способ оплаты",
    "payments.creditCard": "Кредитная карта",
    "payments.bankTransfer": "Банковский перевод",
    "payments.applePay": "Apple Pay",
    "payments.stcPay": "STC Pay",
    "payments.confirmPayment": "Подтвердить оплату",
    "payments.processing": "Обработка...",
    "payments.success": "Оплата успешна!",
    "payments.contractGenerated": "Контракт сгенерирован автоматически",
    "payments.noPending": "Нет ожидающих платежей",
    "payments.totalPaid": "Всего оплачено",
    "payments.totalRemaining": "Всего осталось",

    "contracts.title": "Контракты и соглашения",
    "contracts.noContracts": "Нет контрактов",
    "contracts.noContractsDesc": "Контракт генерируется после полной оплаты",
    "contracts.download": "Скачать PDF",
    "contracts.share": "Поделиться",
    "contracts.signed": "Подписан",
    "contracts.pendingSignature": "Ожидает подписи",
    "contracts.draft": "Черновик",
    "contracts.sentVia": "Отправлен через",
    "contracts.value": "Стоимость контракта",
    "contracts.booth": "Стенд",
    "contracts.expiry": "Срок действия",
    "contracts.steps": "Этапы выдачи контракта",
    "contracts.step1": "Верификация аккаунта (KYC)",
    "contracts.step2": "Бронирование площади",
    "contracts.step3": "Полная оплата",
    "contracts.step4": "Автоматическая генерация контракта",

    "ops.title": "Операции и сервисы",
    "ops.requestService": "Запросить услугу",
    "ops.permits": "Разрешения",
    "ops.maintenance": "Обслуживание",
    "ops.logistics": "Логистика",

    "analytics.title": "Аналитика и отчёты",
    "analytics.export": "Экспорт отчёта",
    "analytics.aiInsights": "AI-аналитика",
    "analytics.totalPaid": "Всего оплачено",
    "analytics.bookings": "Бронирования",
    "analytics.occupancy": "Заполняемость",
    "analytics.openEvents": "Открытые мероприятия",
    "analytics.monthlyDist": "Распределение мероприятий 2026",
    "analytics.categoryDist": "По категориям",
    "analytics.cityUnits": "По городам",

    "ai.title": "AI-ассистент",
    "ai.subtitle": "Умный AI-ассистент — MAHAM AI",
    "ai.online": "Онлайн",
    "ai.thinking": "AI анализирует данные...",
    "ai.placeholder": "Спросите AI о мероприятиях, бронированиях...",
    "ai.general": "Общий чат",
    "ai.analysis": "Аналитика",
    "ai.recommendation": "Рекомендации",

    "kyc.title": "Верификация аккаунта",
    "kyc.subtitle": "Подтвердите личность для начала бронирования",
    "kyc.personal": "Личные данные",
    "kyc.company": "Данные компании",
    "kyc.bank": "Банковский счёт",
    "kyc.documents": "Загрузка документов",
    "kyc.declaration": "Юридическое заявление",
    "kyc.complete": "Верификация завершена",
    "kyc.next": "Далее",
    "kyc.prev": "Назад",
    "kyc.submit": "Отправить на проверку",
    "kyc.uploadFile": "Загрузить файл",
    "kyc.uploaded": "Загружено",
    "kyc.required": "Обязательно",
    "kyc.optional": "Необязательно",

    "settings.title": "Настройки",
    "settings.profile": "Профиль",
    "settings.notifications": "Уведомления",
    "settings.security": "Безопасность",
    "settings.language": "Язык",
    "settings.theme": "Тема",
    "settings.dark": "Тёмная",
    "settings.light": "Светлая",

    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.confirm": "Подтвердить",
    "common.close": "Закрыть",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.success": "Успешно",
    "common.comingSoon": "Скоро",
    "common.viewDetails": "Подробнее",
    "common.search": "Поиск",
    "common.filter": "Фильтр",
    "common.sort": "Сортировка",
    "common.total": "Всего",
    "common.status": "Статус",
    "common.date": "Дата",
    "common.amount": "Сумма",
    "common.actions": "Действия",
    "common.zone": "Зона",
    "common.type": "Тип",
    "common.size": "Площадь",
    "common.price": "Цена",
    "common.services": "Услуги",
    "common.notifications": "Уведомления",
    "common.markAllRead": "Отметить все как прочитанные",
    "common.noNotifications": "Нет уведомлений",
  },

  // ═══════════════════════════════════════
  // PERSIAN / FARSI (فارسی)
  // ═══════════════════════════════════════
  fa: {
    "nav.dashboard": "داشبورد",
    "nav.expos": "نمایشگاه‌ها و رویدادها",
    "nav.bookings": "رزروها",
    "nav.payments": "پرداخت‌ها",
    "nav.contracts": "قراردادها",
    "nav.operations": "عملیات",
    "nav.analytics": "تحلیل‌ها",
    "nav.ai": "دستیار هوشمند",
    "nav.map": "نقشه",
    "nav.kyc": "احراز هویت",
    "nav.help": "مرکز راهنمایی",
    "nav.settings": "تنظیمات",
    "nav.logout": "خروج",

    "home.title": "پرتال هوشمند بازرگان",
    "home.subtitle": "Smart Trader Portal",
    "home.desc": "پلتفرم جامع مبتنی بر هوش مصنوعی برای مدیریت رزرو نمایشگاه‌ها، کنفرانس‌ها و رویدادها",
    "home.desc2": "از مرور تا رزرو و عملیات — همه در یک مکان",
    "home.login": "ورود به داشبورد",
    "home.browse": "مرور نمایشگاه‌ها و رزرو",
    "home.map": "مشاهده نقشه",
    "home.stat.exhibitors": "غرفه‌داران و سرمایه‌گذاران",
    "home.stat.events": "نمایشگاه‌ها و رویدادها",
    "home.stat.units": "واحدهای تجاری",
    "home.stat.satisfaction": "رضایت مشتریان",

    "auth.phone": "شماره موبایل",
    "auth.phone.placeholder": "05XXXXXXXX",
    "auth.sendOtp": "ارسال کد تأیید",
    "auth.otp": "کد تأیید",
    "auth.otp.placeholder": "کد ۴ رقمی را وارد کنید",
    "auth.verify": "تأیید",
    "auth.name": "نام کامل",
    "auth.company": "نام شرکت",
    "auth.activity": "فعالیت تجاری",
    "auth.region": "منطقه",
    "auth.complete": "تکمیل ثبت‌نام",
    "auth.welcome": "به Maham Expo خوش آمدید",
    "auth.login.title": "ورود",
    "auth.register.title": "ایجاد حساب جدید",

    "dash.title": "داشبورد",
    "dash.activeBookings": "رزروهای فعال",
    "dash.contracts": "قراردادهای صادر شده",
    "dash.paid": "پرداخت شده (ریال)",
    "dash.openEvents": "رویدادهای باز",
    "dash.recentBookings": "آخرین رزروها",
    "dash.quickActions": "اقدامات سریع",
    "dash.upcomingEvents": "رویدادهای آینده",
    "dash.viewAll": "مشاهده همه",
    "dash.noBookings": "هنوز رزروی ندارید",
    "dash.browseStart": "نمایشگاه‌ها را مرور کنید و رزرو کنید",
    "dash.bookNew": "رزرو واحد جدید",
    "dash.viewContracts": "مشاهده قراردادها",
    "dash.makePayment": "پرداخت",
    "dash.requestPermit": "درخواست مجوز",
    "dash.unitsAvailable": "واحد موجود",

    "expos.title": "مرور نمایشگاه‌ها و رویدادهای ۲۰۲۶",
    "expos.search": "جستجوی نمایشگاه، رویداد یا مکان...",
    "expos.all": "همه",
    "expos.city": "شهر",
    "expos.sortBy": "مرتب‌سازی بر اساس",
    "expos.sort.date": "تاریخ",
    "expos.sort.price": "قیمت",
    "expos.sort.rating": "امتیاز",
    "expos.sort.availability": "واحدهای موجود",
    "expos.resetFilters": "بازنشانی فیلترها",
    "expos.results": "نتیجه",
    "expos.for": "برای",
    "expos.noResults": "نتیجه‌ای یافت نشد",
    "expos.tryDifferent": "فیلترها یا عبارت جستجو را تغییر دهید",
    "expos.featured": "ویژه",
    "expos.open": "باز برای رزرو",
    "expos.closingSoon": "به زودی بسته می‌شود",
    "expos.full": "تکمیل شده",
    "expos.upcoming": "به زودی",
    "expos.availableUnits": "واحدهای موجود",
    "expos.priceRange": "محدوده قیمت",
    "expos.location": "موقعیت",
    "expos.period": "دوره",
    "expos.venue": "محل برگزاری",
    "expos.category": "دسته‌بندی",
    "expos.visitors": "بازدیدکنندگان مورد انتظار",
    "expos.occupancy": "نرخ اشغال",
    "expos.total": "کل",
    "expos.viewMap": "مشاهده نقشه و غرفه‌ها",
    "expos.bookNow": "رزرو کنید",
    "expos.notifyOpen": "هنگام باز شدن رزرو اطلاع دهید",
    "expos.waitlist": "لیست انتظار",
    "expos.selectUnit": "واحد مورد نظر را انتخاب کنید",
    "expos.bookUnit": "رزرو این واحد",
    "expos.deposit": "بیعانه",
    "expos.kycRequired": "احراز هویت قبل از رزرو الزامی است",
    "expos.eventsAvailable": "رویداد موجود",
    "expos.closingSoonCount": "به زودی بسته می‌شود",
    "expos.totalUnits": "کل واحدها",
    "expos.availableUnitsCount": "واحدهای موجود",
    "expos.remainingCategories": "دسته‌بندی‌های بیشتر",
    "expos.sar": "ریال",

    "bookings.title": "مدیریت رزروها",
    "bookings.all": "همه",
    "bookings.pending": "در انتظار پرداخت",
    "bookings.confirmed": "تأیید شده",
    "bookings.active": "فعال",
    "bookings.cancelled": "لغو شده",
    "bookings.noBookings": "رزروی وجود ندارد",
    "bookings.startBrowsing": "نمایشگاه‌ها را مرور کنید",
    "bookings.goToPayments": "تکمیل پرداخت",
    "bookings.viewContract": "مشاهده قرارداد",
    "bookings.details": "جزئیات رزرو",
    "bookings.paid": "پرداخت شده",
    "bookings.remaining": "باقیمانده",

    "payments.title": "پرداخت‌ها و فاکتورها",
    "payments.pending": "پرداخت‌های معلق",
    "payments.completed": "تکمیل شده",
    "payments.all": "همه",
    "payments.payNow": "پرداخت کنید",
    "payments.amount": "مبلغ",
    "payments.method": "روش پرداخت",
    "payments.creditCard": "کارت اعتباری",
    "payments.bankTransfer": "انتقال بانکی",
    "payments.applePay": "Apple Pay",
    "payments.stcPay": "STC Pay",
    "payments.confirmPayment": "تأیید پرداخت",
    "payments.processing": "در حال پردازش...",
    "payments.success": "پرداخت موفق!",
    "payments.contractGenerated": "قرارداد به صورت خودکار صادر شد",
    "payments.noPending": "پرداخت معلقی وجود ندارد",
    "payments.totalPaid": "کل پرداخت شده",
    "payments.totalRemaining": "کل باقیمانده",

    "contracts.title": "قراردادها و توافق‌نامه‌ها",
    "contracts.noContracts": "قراردادی صادر نشده",
    "contracts.noContractsDesc": "قرارداد پس از پرداخت کامل به صورت خودکار صادر می‌شود",
    "contracts.download": "دانلود PDF",
    "contracts.share": "اشتراک‌گذاری",
    "contracts.signed": "امضا شده",
    "contracts.pendingSignature": "در انتظار امضا",
    "contracts.draft": "پیش‌نویس",
    "contracts.sentVia": "ارسال شده از طریق",
    "contracts.value": "ارزش قرارداد",
    "contracts.booth": "غرفه",
    "contracts.expiry": "تاریخ انقضا",
    "contracts.steps": "مراحل صدور قرارداد",
    "contracts.step1": "احراز هویت (KYC)",
    "contracts.step2": "رزرو واحد در نمایشگاه",
    "contracts.step3": "تکمیل پرداخت کامل",
    "contracts.step4": "صدور خودکار قرارداد",

    "ops.title": "عملیات و خدمات",
    "ops.requestService": "درخواست خدمات",
    "ops.permits": "مجوزها",
    "ops.maintenance": "نگهداری",
    "ops.logistics": "لجستیک",

    "analytics.title": "تحلیل‌ها و گزارش‌ها",
    "analytics.export": "خروجی گزارش",
    "analytics.aiInsights": "بینش‌های هوش مصنوعی",
    "analytics.totalPaid": "کل پرداخت شده",
    "analytics.bookings": "رزروها",
    "analytics.occupancy": "نرخ اشغال",
    "analytics.openEvents": "رویدادهای باز",
    "analytics.monthlyDist": "توزیع ماهانه رویدادهای ۲۰۲۶",
    "analytics.categoryDist": "بر اساس دسته‌بندی",
    "analytics.cityUnits": "بر اساس شهر",

    "ai.title": "دستیار هوشمند",
    "ai.subtitle": "دستیار هوشمند AI — توسط MAHAM AI",
    "ai.online": "آنلاین",
    "ai.thinking": "AI در حال تحلیل داده‌ها...",
    "ai.placeholder": "از AI درباره رویدادها، رزروها بپرسید...",
    "ai.general": "گفتگوی عمومی",
    "ai.analysis": "تحلیل‌ها",
    "ai.recommendation": "پیشنهادها",

    "kyc.title": "احراز هویت حساب",
    "kyc.subtitle": "هویت خود را تأیید کنید تا رزرو را شروع کنید",
    "kyc.personal": "اطلاعات شخصی",
    "kyc.company": "اطلاعات شرکت",
    "kyc.bank": "حساب بانکی",
    "kyc.documents": "بارگذاری مدارک",
    "kyc.declaration": "اعلامیه حقوقی",
    "kyc.complete": "احراز هویت تکمیل شد",
    "kyc.next": "بعدی",
    "kyc.prev": "قبلی",
    "kyc.submit": "ارسال برای بررسی",
    "kyc.uploadFile": "بارگذاری فایل",
    "kyc.uploaded": "بارگذاری شد",
    "kyc.required": "الزامی",
    "kyc.optional": "اختیاری",

    "settings.title": "تنظیمات",
    "settings.profile": "پروفایل",
    "settings.notifications": "اعلان‌ها",
    "settings.security": "امنیت",
    "settings.language": "زبان",
    "settings.theme": "تم",
    "settings.dark": "تیره",
    "settings.light": "روشن",

    "common.save": "ذخیره",
    "common.cancel": "لغو",
    "common.confirm": "تأیید",
    "common.close": "بستن",
    "common.back": "بازگشت",
    "common.next": "بعدی",
    "common.loading": "در حال بارگذاری...",
    "common.error": "خطا رخ داد",
    "common.success": "موفقیت‌آمیز",
    "common.comingSoon": "به زودی",
    "common.viewDetails": "مشاهده جزئیات",
    "common.search": "جستجو",
    "common.filter": "فیلتر",
    "common.sort": "مرتب‌سازی",
    "common.total": "کل",
    "common.status": "وضعیت",
    "common.date": "تاریخ",
    "common.amount": "مبلغ",
    "common.actions": "اقدامات",
    "common.zone": "منطقه",
    "common.type": "نوع",
    "common.size": "اندازه",
    "common.price": "قیمت",
    "common.services": "خدمات",
    "common.notifications": "اعلان‌ها",
    "common.markAllRead": "همه را خوانده علامت بزنید",
    "common.noNotifications": "اعلانی وجود ندارد",
  },

  // ═══════════════════════════════════════
  // TURKISH (Türkçe)
  // ═══════════════════════════════════════
  tr: {
    "nav.dashboard": "Kontrol Paneli",
    "nav.expos": "Fuarlar ve Etkinlikler",
    "nav.bookings": "Rezervasyonlar",
    "nav.payments": "Ödemeler",
    "nav.contracts": "Sözleşmeler",
    "nav.operations": "Operasyonlar",
    "nav.analytics": "Analitik",
    "nav.ai": "AI Asistan",
    "nav.map": "Harita",
    "nav.kyc": "Hesap Doğrulama",
    "nav.help": "Yardım Merkezi",
    "nav.settings": "Ayarlar",
    "nav.logout": "Çıkış",

    "home.title": "Akıllı Tüccar Portalı",
    "home.subtitle": "Smart Trader Portal",
    "home.desc": "Fuar, konferans ve etkinlik rezervasyonlarınızı yönetmek için kapsamlı AI destekli platform",
    "home.desc2": "Göz atmadan rezervasyona ve operasyonlara — hepsi tek yerde",
    "home.login": "Panele Giriş",
    "home.browse": "Fuarları İncele ve Rezerve Et",
    "home.map": "Haritayı Görüntüle",
    "home.stat.exhibitors": "Katılımcı ve Yatırımcı",
    "home.stat.events": "Fuar ve Etkinlik",
    "home.stat.units": "Ticari Alan",
    "home.stat.satisfaction": "Müşteri Memnuniyeti",

    "auth.phone": "Telefon Numarası",
    "auth.phone.placeholder": "05XXXXXXXX",
    "auth.sendOtp": "Doğrulama Kodu Gönder",
    "auth.otp": "Doğrulama Kodu",
    "auth.otp.placeholder": "4 haneli kodu girin",
    "auth.verify": "Doğrula",
    "auth.name": "Tam Ad",
    "auth.company": "Şirket Adı",
    "auth.activity": "İş Faaliyeti",
    "auth.region": "Bölge",
    "auth.complete": "Kaydı Tamamla",
    "auth.welcome": "Maham Expo'ya Hoş Geldiniz",
    "auth.login.title": "Giriş",
    "auth.register.title": "Yeni Hesap Oluştur",

    "dash.title": "Kontrol Paneli",
    "dash.activeBookings": "Aktif Rezervasyonlar",
    "dash.contracts": "Düzenlenen Sözleşmeler",
    "dash.paid": "Ödenen (SAR)",
    "dash.openEvents": "Açık Etkinlikler",
    "dash.recentBookings": "Son Rezervasyonlar",
    "dash.quickActions": "Hızlı İşlemler",
    "dash.upcomingEvents": "Yaklaşan Etkinlikler",
    "dash.viewAll": "Tümünü Gör",
    "dash.noBookings": "Henüz rezervasyon yok",
    "dash.browseStart": "Fuarları inceleyin ve rezervasyon yapın",
    "dash.bookNew": "Yeni Alan Rezerve Et",
    "dash.viewContracts": "Sözleşmeleri Gör",
    "dash.makePayment": "Ödeme Yap",
    "dash.requestPermit": "İzin Talep Et",
    "dash.unitsAvailable": "müsait alan",

    "expos.title": "2026 Fuarları ve Etkinlikleri",
    "expos.search": "Fuar, etkinlik veya mekan ara...",
    "expos.all": "Tümü",
    "expos.city": "Şehir",
    "expos.sortBy": "Sırala",
    "expos.sort.date": "Tarih",
    "expos.sort.price": "Fiyat",
    "expos.sort.rating": "Puan",
    "expos.sort.availability": "Müsait Alanlar",
    "expos.resetFilters": "Filtreleri Sıfırla",
    "expos.results": "sonuç",
    "expos.for": "için",
    "expos.noResults": "Eşleşen sonuç yok",
    "expos.tryDifferent": "Filtreleri veya arama terimini değiştirin",
    "expos.featured": "Öne Çıkan",
    "expos.open": "Rezervasyona Açık",
    "expos.closingSoon": "Yakında Kapanıyor",
    "expos.full": "Tamamen Dolu",
    "expos.upcoming": "Yakında",
    "expos.availableUnits": "Müsait Alanlar",
    "expos.priceRange": "Fiyat Aralığı",
    "expos.location": "Konum",
    "expos.period": "Dönem",
    "expos.venue": "Mekan",
    "expos.category": "Kategori",
    "expos.visitors": "Beklenen Ziyaretçi",
    "expos.occupancy": "Doluluk Oranı",
    "expos.total": "Toplam",
    "expos.viewMap": "Harita ve Stantları Gör",
    "expos.bookNow": "Şimdi Rezerve Et",
    "expos.notifyOpen": "Açıldığında bildir",
    "expos.waitlist": "Bekleme Listesi",
    "expos.selectUnit": "Rezerve edilecek alanı seçin",
    "expos.bookUnit": "Bu Alanı Rezerve Et",
    "expos.deposit": "Depozito",
    "expos.kycRequired": "Rezervasyon için hesap doğrulaması gerekli",
    "expos.eventsAvailable": "Müsait Etkinlik",
    "expos.closingSoonCount": "Yakında Kapanıyor",
    "expos.totalUnits": "Toplam Alan",
    "expos.availableUnitsCount": "Müsait Alan",
    "expos.remainingCategories": "Diğer Kategoriler",
    "expos.sar": "SAR",

    "bookings.title": "Rezervasyon Yönetimi",
    "bookings.all": "Tümü",
    "bookings.pending": "Ödeme Bekliyor",
    "bookings.confirmed": "Onaylandı",
    "bookings.active": "Aktif",
    "bookings.cancelled": "İptal Edildi",
    "bookings.noBookings": "Rezervasyon yok",
    "bookings.startBrowsing": "Fuarları inceleyin ve alan rezerve edin",
    "bookings.goToPayments": "Ödemeyi Tamamla",
    "bookings.viewContract": "Sözleşmeyi Gör",
    "bookings.details": "Rezervasyon Detayları",
    "bookings.paid": "Ödendi",
    "bookings.remaining": "Kalan",

    "payments.title": "Ödemeler ve Faturalar",
    "payments.pending": "Bekleyen Ödemeler",
    "payments.completed": "Tamamlanan",
    "payments.all": "Tümü",
    "payments.payNow": "Şimdi Öde",
    "payments.amount": "Tutar",
    "payments.method": "Ödeme Yöntemi",
    "payments.creditCard": "Kredi Kartı",
    "payments.bankTransfer": "Banka Havalesi",
    "payments.applePay": "Apple Pay",
    "payments.stcPay": "STC Pay",
    "payments.confirmPayment": "Ödemeyi Onayla",
    "payments.processing": "İşleniyor...",
    "payments.success": "Ödeme Başarılı!",
    "payments.contractGenerated": "Sözleşme otomatik oluşturuldu",
    "payments.noPending": "Bekleyen ödeme yok",
    "payments.totalPaid": "Toplam Ödenen",
    "payments.totalRemaining": "Toplam Kalan",

    "contracts.title": "Sözleşmeler ve Anlaşmalar",
    "contracts.noContracts": "Sözleşme yok",
    "contracts.noContractsDesc": "Sözleşme tam ödeme sonrası otomatik oluşturulur",
    "contracts.download": "PDF İndir",
    "contracts.share": "Paylaş",
    "contracts.signed": "İmzalandı",
    "contracts.pendingSignature": "İmza Bekliyor",
    "contracts.draft": "Taslak",
    "contracts.sentVia": "Gönderildi",
    "contracts.value": "Sözleşme Değeri",
    "contracts.booth": "Stant",
    "contracts.expiry": "Son Tarih",
    "contracts.steps": "Sözleşme Düzenleme Adımları",
    "contracts.step1": "Hesap Doğrulama (KYC)",
    "contracts.step2": "Fuarda alan rezerve et",
    "contracts.step3": "Tam ödemeyi tamamla",
    "contracts.step4": "Sözleşme otomatik oluşturulur",

    "ops.title": "Operasyonlar ve Hizmetler",
    "ops.requestService": "Hizmet Talep Et",
    "ops.permits": "İzinler",
    "ops.maintenance": "Bakım",
    "ops.logistics": "Lojistik",

    "analytics.title": "Analitik ve Raporlar",
    "analytics.export": "Rapor Dışa Aktar",
    "analytics.aiInsights": "AI Öngörüleri",
    "analytics.totalPaid": "Toplam Ödenen",
    "analytics.bookings": "Rezervasyonlar",
    "analytics.occupancy": "Doluluk",
    "analytics.openEvents": "Açık Etkinlikler",
    "analytics.monthlyDist": "2026 Aylık Etkinlik Dağılımı",
    "analytics.categoryDist": "Kategoriye Göre",
    "analytics.cityUnits": "Şehre Göre",

    "ai.title": "AI Asistan",
    "ai.subtitle": "Akıllı AI Asistan — MAHAM AI",
    "ai.online": "Çevrimiçi",
    "ai.thinking": "AI veri analiz ediyor...",
    "ai.placeholder": "AI'ya etkinlikler, rezervasyonlar hakkında sorun...",
    "ai.general": "Genel Sohbet",
    "ai.analysis": "Analitik",
    "ai.recommendation": "Öneriler",

    "kyc.title": "Hesap Doğrulama",
    "kyc.subtitle": "Rezervasyona başlamak için kimliğinizi doğrulayın",
    "kyc.personal": "Kişisel Bilgiler",
    "kyc.company": "Şirket Bilgileri",
    "kyc.bank": "Banka Hesabı",
    "kyc.documents": "Belge Yükleme",
    "kyc.declaration": "Yasal Beyan",
    "kyc.complete": "Doğrulama Tamamlandı",
    "kyc.next": "İleri",
    "kyc.prev": "Geri",
    "kyc.submit": "İncelemeye Gönder",
    "kyc.uploadFile": "Dosya Yükle",
    "kyc.uploaded": "Yüklendi",
    "kyc.required": "Zorunlu",
    "kyc.optional": "İsteğe Bağlı",

    "settings.title": "Ayarlar",
    "settings.profile": "Profil",
    "settings.notifications": "Bildirimler",
    "settings.security": "Güvenlik",
    "settings.language": "Dil",
    "settings.theme": "Tema",
    "settings.dark": "Koyu",
    "settings.light": "Açık",

    "common.save": "Kaydet",
    "common.cancel": "İptal",
    "common.confirm": "Onayla",
    "common.close": "Kapat",
    "common.back": "Geri",
    "common.next": "İleri",
    "common.loading": "Yükleniyor...",
    "common.error": "Hata oluştu",
    "common.success": "Başarılı",
    "common.comingSoon": "Yakında",
    "common.viewDetails": "Detayları Gör",
    "common.search": "Ara",
    "common.filter": "Filtrele",
    "common.sort": "Sırala",
    "common.total": "Toplam",
    "common.status": "Durum",
    "common.date": "Tarih",
    "common.amount": "Tutar",
    "common.actions": "İşlemler",
    "common.zone": "Bölge",
    "common.type": "Tür",
    "common.size": "Alan",
    "common.price": "Fiyat",
    "common.services": "Hizmetler",
    "common.notifications": "Bildirimler",
    "common.markAllRead": "Tümünü okundu işaretle",
    "common.noNotifications": "Bildirim yok",
  },
};
